version: "3.8"
services:
  kegcomponents:
    volumes:
      - components-sync:${DOC_APP_PATH}:nocopy
      - cli-sync:/keg/keg-cli:nocopy
volumes:
  components-sync:
    external:
      name: "components-unison-sync"
  cli-sync:
    external:
      name: "cli-unison-sync"