version: "3.8"
services:
  keg-components:
    image: ${IMAGE}
    tty: true
    stdin_open: true
    privileged: true
    build:
      context: ${KEG_CONTEXT_PATH}
      dockerfile: ${KEG_DOCKER_FILE}
      args:
        GIT_COMPONENTS_URL: ${GIT_COMPONENTS_URL}
        GIT_KEY: ${GIT_KEY}
        DOC_APP_PATH: ${DOC_APP_PATH}
    container_name: ${CONTAINER_NAME}
    environment:
      - ENV
      - DOC_APP_PATH
      - DOC_CLI_PATH
      - DOC_COMPONENTS_PATH
      - DOC_RETHEME_PATH
      - GIT_CLI_URL
      - GIT_COMPONENTS_URL
      - GIT_RETHEME_URL
      - IMAGE_FROM
      - KEG_EXEC_CMD
      - KEG_NM_INSTALL
      - NODE_ENV
    ports:
      - 80:${DOC_APP_PORT}