version: "2"
services:
  tap:
    volumes:
      - tap-sync:/keg/tap:nocopy
      - cli-sync:/keg/keg-cli:nocopy
volumes:
  tap-sync:
    external:
      name: "tap-unison-sync"
  cli-sync:
    external:
      name: "cli-unison-sync"