version: "2"
options:
  compose-file-path: '${KEG_PATH}/cli/scripts/docker/docker-compose.yml'
  compose-dev-file-path: '${KEG_PATH}/cli/scripts/docker/docker-compose-dev.yml'
  verbose: false
  project_root: '${KEG_PATH}'
syncs:
  tap-unison-sync:
    src: '${TAP_PATH}'
    sync_strategy: 'unison'
    max_inotify_watches: 200000
    sync_excludes: [ 'node_modules', '.gitignore', '.git' ]
  cli-unison-sync:
    src: '${CLI_PATH}'
    sync_strategy: 'unison'
    max_inotify_watches: 200000
    sync_excludes: [ '.gitignore', '.git' ]
  core-unison-sync:
    src: '${CORE_PATH}'
    sync_strategy: 'unison'
    max_inotify_watches: 200000
    sync_excludes: [ '.gitignore', '.git' ]

