version: "3.8"
services:
  keg-regulator:
    build:
      context: .
      dockerfile: ./tests/Dockerfile
    tty: true
    stdin_open: true
    privileged: true
    container_name: 'keg-regulator'
    volumes:
      - ./tests/features:/keg/keg-regulator/tests/features
      - ./tests/steps:/keg/keg-regulator/tests/steps
      - ./tests/reports:/keg/keg-regulator/tests/reports
    ports:
      - "4000:4000"
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - TEST_FILTER_TAGS
      - WINDOW_HEIGHT
      - WINDOW_WIDTH
    depends_on:
      - "selenium-hub"
      - "chrome"
      - "firefox"