
env:
  # --- BASE ENV CONTEXT --- #

  CONTEXT_PATH: "{{ cli.paths.cli }}"
  CONTEXT_DOCKER_FILE: "{{ cli.paths.containers }}/base/Dockerfile"
  CONTEXT_VALUES_FILE: "{{ cli.paths.containers }}/base/values.yml"
  COMPOSE_DEFAULT: "{{ cli.paths.containers }}/base/docker-compose.yml"
  # Can also define an override compose file
  # by setting an env as COMPOSE_<ENV>=<path to override> || COMPOSE_BASE_<ENV>=<path to override>
  # Examples:
    # COMPOSE_DEVELOPMENT: "/path/to/override.dev.yml"
    # COMPOSE_CORE_PRODUCTION: "/path/to/override.production.yml"

  # --- DOCKER ENV CONTEXT --- #

  # Image ENVs
  IMAGE: kegbase
  VERSION: "0.0.1"

  # Container ENVs
  CONTAINER_NAME: kegbase
