
name: keg-build-images
on:
  push:
    branches:
      - develop
      - next
  workflow_dispatch:
    inputs:
      cliBranch:
        required: false
        description: "Name of keg-cli git branch to use in this workflow"

jobs:
  build-images:
    name: 'Build Images'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      GIT_TOKEN: ${{ secrets.KEG_ACTION_TOKEN }}
      # TODO: update this back to develop once next-6-0-0 is merged
      DEFAULT_KEG_CLI_BRANCH: next-6-0-0
      KEG_CLI_PATH: ${{ github.workspace }}/keg-cli
      KEG_CLI_USER: lancetipton
      KEG_GLOBAL_CONFIG: ${{ github.workspace }}/keg-cli/.kegConfig/cli.config.json
      KEG_HUB_PATH: ${{ github.workspace }}/keg-hub
    steps:
      - name: Cancel Previous Workflows In Progress
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ secrets.KEG_ACTION_TOKEN }}

      - name: "Clone Keg-CLI"
        id: clone-cli
        run: git -C $GITHUB_WORKSPACE clone --single-branch --branch ${{ github.event.inputs.cliBranch || env.DEFAULT_KEG_CLI_BRANCH }} https://github.com/keghub/keg-cli.git

      - name: "Setup Keg Environment"
        id: setup-environment
        run: cd $GITHUB_WORKSPACE/keg-cli && KEG_HUB_BRANCH=${GITHUB_REF##*/} bash scripts/ci/setupKegEnvironment.sh
        env:
          KEG_ROOT_DIR: ${{ env.KEG_HUB_PATH }}
          KEG_CLI_BRANCH: ${{ github.event.inputs.cliBranch || env.DEFAULT_KEG_CLI_BRANCH }}
          KEG_CLI_USER: lancetipton

      - name: "Link Keg-Hub Taps"
        id: link-taps
        run: cd $KEG_HUB_PATH && bash scripts/ci/linkRepos.sh

      - name: "Build and Push"
        id: build-push-images
        run: cd $KEG_HUB_PATH && bash scripts/ci/buildPushDockerImages.sh
